script_arg <- grep("^--file=", commandArgs(), value = TRUE)
root <- normalizePath(file.path(dirname(normalizePath(sub("^--file=", "", script_arg[1]))), ".."))
source(file.path(root,"environment","check_author_environment.R"))
assert_author_environment(root, write_outputs = FALSE)
output_dir <- Sys.getenv("THESIS_VALIDATION_OUTPUT_DIR", unset = file.path(root,"validation"))
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
source(file.path(root,"src","dgp_kappa.R")); source(file.path(root,"src","author_bc_dml_wrapper.R"))
set.seed(5317); dat <- make_kappa_dataset(generate_kappa_primitives(500L),1)
out <- do.call(rbind,lapply(c(-1,-.9,-.8),function(a) {
  fit <- author_bc_candidate(dat$y,dat$D,dat$X,dat$Z,.5,a,TRUE)
  data.frame(a=a,lambda_intercept=fit$lambda[1],lambda_min=min(fit$lambda),lambda_mean=mean(fit$lambda),lambda_max=max(fit$lambda),W=fit$W)
}))
stopifnot(length(unique(out$lambda_intercept)) > 1)
write.csv(out,file.path(output_dir,"bc_fresh_draw_validation.csv"),row.names=FALSE)
print(out)
